#############################################################################
# Makefile for building: TurboDatabase
# Generated by qmake (3.0) (Qt 5.7.0)
# Project:  TurboDatabase.pro
# Template: app
# Command: /home/ferhan/Qt5.7.0/5.7/gcc_64/bin/qmake -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug -o Makefile TurboDatabase.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_QML_DEBUG -DQT_CORE_LIB
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -g -std=gnu++11 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I/home/ferhan/Qt5.7.0/5.7/gcc_64/include -I/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore -I. -I/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/linux-g++
QMAKE         = /home/ferhan/Qt5.7.0/5.7/gcc_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = TurboDatabase1.0.0
DISTDIR = /media/ferhan/Education_material_and_setups/BS_education_material/semester_6/Algo/Assignment/B_tree_CRUD/TurboDatabase/.tmp/TurboDatabase1.0.0
LINK          = g++
LFLAGS        = -Wl,-rpath,/home/ferhan/Qt5.7.0/5.7/gcc_64/lib
LIBS          = $(SUBLIBS) -L/home/ferhan/Qt5.7.0/5.7/gcc_64/lib -lQt5Core -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		index.cpp \
		btreeindex.cpp \
		database.cpp \
		table.cpp \
		record.cpp 
OBJECTS       = main.o \
		index.o \
		btreeindex.o \
		database.o \
		table.o \
		record.o
DIST          = save \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/features/spec_pre.prf \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/common/unix.conf \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/common/linux.conf \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/common/sanitize.conf \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/common/gcc-base.conf \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/common/gcc-base-unix.conf \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/common/g++-base.conf \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/common/g++-unix.conf \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/qconfig.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dcore.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dextras.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dinput.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dquick.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3drender.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_charts.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_charts_private.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_core.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_datavisualization.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_gamepad.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_help.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_location.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_location_private.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_network.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_purchasing.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_script.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_scxml.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_scxml_private.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_serialbus.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webengine.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webview.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webview_private.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/features/qt_functions.prf \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/features/qt_config.prf \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/linux-g++/qmake.conf \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/features/spec_post.prf \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/features/exclusive_builds.prf \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/features/default_pre.prf \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/features/resolve_config.prf \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/features/default_post.prf \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/features/qml_debug.prf \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/features/warn_on.prf \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/features/qt.prf \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/features/resources.prf \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/features/moc.prf \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/features/unix/thread.prf \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/features/file_copies.prf \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/features/testcase_targets.prf \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/features/exceptions.prf \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/features/yacc.prf \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/features/lex.prf \
		TurboDatabase.pro index.h \
		btreeindex.h \
		database.h \
		table.h \
		record.h main.cpp \
		index.cpp \
		btreeindex.cpp \
		database.cpp \
		table.cpp \
		record.cpp
QMAKE_TARGET  = TurboDatabase
DESTDIR       = 
TARGET        = TurboDatabase


first: all
####### Build rules

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: TurboDatabase.pro /home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/linux-g++/qmake.conf /home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/features/spec_pre.prf \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/common/unix.conf \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/common/linux.conf \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/common/sanitize.conf \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/common/gcc-base.conf \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/common/gcc-base-unix.conf \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/common/g++-base.conf \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/common/g++-unix.conf \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/qconfig.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dcore.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dextras.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dinput.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dquick.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3drender.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_charts.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_charts_private.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_core.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_datavisualization.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_gamepad.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_help.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_location.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_location_private.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_network.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_purchasing.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_script.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_scxml.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_scxml_private.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_serialbus.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webengine.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webview.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webview_private.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/features/qt_functions.prf \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/features/qt_config.prf \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/linux-g++/qmake.conf \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/features/spec_post.prf \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/features/exclusive_builds.prf \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/features/default_pre.prf \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/features/resolve_config.prf \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/features/default_post.prf \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/features/qml_debug.prf \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/features/warn_on.prf \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/features/qt.prf \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/features/resources.prf \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/features/moc.prf \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/features/unix/thread.prf \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/features/file_copies.prf \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/features/testcase_targets.prf \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/features/exceptions.prf \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/features/yacc.prf \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/features/lex.prf \
		TurboDatabase.pro \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/lib/libQt5Core.prl
	$(QMAKE) -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug -o Makefile TurboDatabase.pro
/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/features/spec_pre.prf:
/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/common/unix.conf:
/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/common/linux.conf:
/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/common/sanitize.conf:
/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/common/gcc-base.conf:
/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/common/gcc-base-unix.conf:
/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/common/g++-base.conf:
/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/common/g++-unix.conf:
/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/qconfig.pri:
/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dcore.pri:
/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri:
/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dextras.pri:
/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dextras_private.pri:
/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dinput.pri:
/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri:
/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri:
/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dquick.pri:
/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri:
/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickextras.pri:
/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickextras_private.pri:
/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri:
/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri:
/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3drender.pri:
/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri:
/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri:
/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_charts.pri:
/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_charts_private.pri:
/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri:
/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_concurrent.pri:
/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri:
/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_core.pri:
/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_core_private.pri:
/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_datavisualization.pri:
/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_datavisualization_private.pri:
/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_dbus.pri:
/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri:
/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_designer.pri:
/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_designer_private.pri:
/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri:
/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_gamepad.pri:
/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_gamepad_private.pri:
/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_gui.pri:
/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_gui_private.pri:
/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_help.pri:
/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_help_private.pri:
/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_location.pri:
/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_location_private.pri:
/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_multimedia.pri:
/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri:
/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_network.pri:
/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_network_private.pri:
/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_nfc.pri:
/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri:
/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_opengl.pri:
/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri:
/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri:
/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_positioning.pri:
/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri:
/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_printsupport.pri:
/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri:
/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_purchasing.pri:
/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_purchasing_private.pri:
/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_qml.pri:
/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_qml_private.pri:
/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_qmltest.pri:
/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri:
/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_quick.pri:
/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_quick_private.pri:
/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri:
/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_script.pri:
/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_script_private.pri:
/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_scripttools.pri:
/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri:
/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_scxml.pri:
/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_scxml_private.pri:
/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_sensors.pri:
/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri:
/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_serialbus.pri:
/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri:
/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_serialport.pri:
/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri:
/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_sql.pri:
/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_sql_private.pri:
/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_svg.pri:
/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_svg_private.pri:
/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_testlib.pri:
/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri:
/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri:
/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_uitools.pri:
/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri:
/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webchannel.pri:
/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri:
/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webengine.pri:
/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri:
/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri:
/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_websockets.pri:
/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri:
/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webview.pri:
/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webview_private.pri:
/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_widgets.pri:
/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri:
/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_x11extras.pri:
/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri:
/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_xml.pri:
/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_xml_private.pri:
/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/features/qt_functions.prf:
/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/features/qt_config.prf:
/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/linux-g++/qmake.conf:
/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/features/spec_post.prf:
/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/features/exclusive_builds.prf:
/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/features/default_pre.prf:
/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/features/resolve_config.prf:
/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/features/default_post.prf:
/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/features/qml_debug.prf:
/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/features/warn_on.prf:
/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/features/qt.prf:
/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/features/resources.prf:
/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/features/moc.prf:
/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/features/unix/thread.prf:
/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/features/file_copies.prf:
/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/features/testcase_targets.prf:
/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/features/exceptions.prf:
/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/features/yacc.prf:
/home/ferhan/Qt5.7.0/5.7/gcc_64/mkspecs/features/lex.prf:
TurboDatabase.pro:
/home/ferhan/Qt5.7.0/5.7/gcc_64/lib/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug -o Makefile TurboDatabase.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents index.h btreeindex.h database.h table.h record.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp index.cpp btreeindex.cpp database.cpp table.cpp record.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

main.o: main.cpp /home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/QCoreApplication \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qcoreapplication.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qglobal.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qconfig.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qfeatures.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qsystemdetection.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qprocessordetection.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qcompilerdetection.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qtypeinfo.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qtypetraits.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qisenum.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qsysinfo.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qlogging.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qflags.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qatomic.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qbasicatomic.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qgenericatomic.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qatomic_cxx11.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qatomic_msvc.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qglobalstatic.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qmutex.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qnumeric.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qversiontagging.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qstring.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qchar.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qbytearray.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qrefcount.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qnamespace.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qarraydata.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qstringbuilder.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qobject.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qobjectdefs.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qlist.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qalgorithms.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qiterator.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qhashfunctions.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qpair.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qbytearraylist.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qstringlist.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qregexp.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qstringmatcher.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qcoreevent.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qscopedpointer.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qmetatype.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qvarlengtharray.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qcontainerfwd.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qobject_impl.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qeventloop.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qhash.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qdebug.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qmap.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qtextstream.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qiodevice.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qlocale.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qvariant.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qshareddata.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qvector.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qpoint.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qset.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qcontiguouscache.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qsharedpointer.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qsharedpointer_impl.h \
		database.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/QList \
		table.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/QHash \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/QString \
		record.h \
		btreeindex.h \
		index.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

index.o: index.cpp index.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/QString \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qstring.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qchar.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qglobal.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qconfig.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qfeatures.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qsystemdetection.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qprocessordetection.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qcompilerdetection.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qtypeinfo.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qtypetraits.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qisenum.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qsysinfo.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qlogging.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qflags.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qatomic.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qbasicatomic.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qgenericatomic.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qatomic_cxx11.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qatomic_msvc.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qglobalstatic.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qmutex.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qnumeric.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qversiontagging.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qbytearray.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qrefcount.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qnamespace.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qarraydata.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qstringbuilder.h \
		record.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/QHash \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qhash.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qiterator.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qlist.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qalgorithms.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qhashfunctions.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qpair.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qbytearraylist.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qstringlist.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qregexp.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qstringmatcher.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/QList \
		table.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o index.o index.cpp

btreeindex.o: btreeindex.cpp btreeindex.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/QString \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qstring.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qchar.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qglobal.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qconfig.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qfeatures.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qsystemdetection.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qprocessordetection.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qcompilerdetection.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qtypeinfo.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qtypetraits.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qisenum.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qsysinfo.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qlogging.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qflags.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qatomic.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qbasicatomic.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qgenericatomic.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qatomic_cxx11.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qatomic_msvc.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qglobalstatic.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qmutex.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qnumeric.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qversiontagging.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qbytearray.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qrefcount.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qnamespace.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qarraydata.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qstringbuilder.h \
		index.h \
		record.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/QHash \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qhash.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qiterator.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qlist.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qalgorithms.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qhashfunctions.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qpair.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qbytearraylist.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qstringlist.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qregexp.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qstringmatcher.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/QList \
		table.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/QDebug \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qdebug.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qmap.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qtextstream.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qiodevice.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qobject.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qobjectdefs.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qcoreevent.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qscopedpointer.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qmetatype.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qvarlengtharray.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qcontainerfwd.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qobject_impl.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qlocale.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qvariant.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qshareddata.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qvector.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qpoint.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qset.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qcontiguouscache.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qsharedpointer.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qsharedpointer_impl.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o btreeindex.o btreeindex.cpp

database.o: database.cpp database.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/QList \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qlist.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qalgorithms.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qglobal.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qconfig.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qfeatures.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qsystemdetection.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qprocessordetection.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qcompilerdetection.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qtypeinfo.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qtypetraits.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qisenum.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qsysinfo.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qlogging.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qflags.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qatomic.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qbasicatomic.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qgenericatomic.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qatomic_cxx11.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qatomic_msvc.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qglobalstatic.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qmutex.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qnumeric.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qversiontagging.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qiterator.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qrefcount.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qarraydata.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qhashfunctions.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qchar.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qpair.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qbytearraylist.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qbytearray.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qnamespace.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qstring.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qstringbuilder.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qstringlist.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qregexp.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qstringmatcher.h \
		table.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/QHash \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qhash.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/QString \
		record.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/QFile \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qfile.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qfiledevice.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qiodevice.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qobject.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qobjectdefs.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qcoreevent.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qscopedpointer.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qmetatype.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qvarlengtharray.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qcontainerfwd.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qobject_impl.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/QDebug \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qdebug.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qmap.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qtextstream.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qlocale.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qvariant.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qshareddata.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qvector.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qpoint.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qset.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qcontiguouscache.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qsharedpointer.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qsharedpointer_impl.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o database.o database.cpp

table.o: table.cpp table.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/QHash \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qhash.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qchar.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qglobal.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qconfig.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qfeatures.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qsystemdetection.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qprocessordetection.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qcompilerdetection.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qtypeinfo.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qtypetraits.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qisenum.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qsysinfo.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qlogging.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qflags.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qatomic.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qbasicatomic.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qgenericatomic.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qatomic_cxx11.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qatomic_msvc.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qglobalstatic.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qmutex.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qnumeric.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qversiontagging.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qiterator.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qlist.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qalgorithms.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qrefcount.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qarraydata.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qhashfunctions.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qpair.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qbytearraylist.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qbytearray.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qnamespace.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qstring.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qstringbuilder.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qstringlist.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qregexp.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qstringmatcher.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/QString \
		record.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/QList \
		index.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/QtDebug \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qdebug.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qmap.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qtextstream.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qiodevice.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qobject.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qobjectdefs.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qcoreevent.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qscopedpointer.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qmetatype.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qvarlengtharray.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qcontainerfwd.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qobject_impl.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qlocale.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qvariant.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qshareddata.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qvector.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qpoint.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qset.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qcontiguouscache.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qsharedpointer.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qsharedpointer_impl.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o table.o table.cpp

record.o: record.cpp record.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/QHash \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qhash.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qchar.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qglobal.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qconfig.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qfeatures.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qsystemdetection.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qprocessordetection.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qcompilerdetection.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qtypeinfo.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qtypetraits.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qisenum.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qsysinfo.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qlogging.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qflags.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qatomic.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qbasicatomic.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qgenericatomic.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qatomic_cxx11.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qatomic_msvc.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qglobalstatic.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qmutex.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qnumeric.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qversiontagging.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qiterator.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qlist.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qalgorithms.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qrefcount.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qarraydata.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qhashfunctions.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qpair.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qbytearraylist.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qbytearray.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qnamespace.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qstring.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qstringbuilder.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qstringlist.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qregexp.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qstringmatcher.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/QList \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/QString \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/QtDebug \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qdebug.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qmap.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qtextstream.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qiodevice.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qobject.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qobjectdefs.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qcoreevent.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qscopedpointer.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qmetatype.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qvarlengtharray.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qcontainerfwd.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qobject_impl.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qlocale.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qvariant.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qshareddata.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qvector.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qpoint.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qset.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qcontiguouscache.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qsharedpointer.h \
		/home/ferhan/Qt5.7.0/5.7/gcc_64/include/QtCore/qsharedpointer_impl.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o record.o record.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

